name: {{{moduleName}}}
options:
  bundleIdPrefix: {{{bundleIdPrefix}}}
targets:
  {{{moduleName}}}:
    type: framework
    platform: iOS
    sources:
      - Sources
    info:
      path: Sources/{{{moduleName}}}/Info.plist
    {{#if hasDependenciesOrStaticAssets}}
    dependencies:
      {{#if hasStaticAssets}}
      - target: Static
        embed: true
      {{/if}}
      {{#each dependencies}}
      - carthage: "{{{this.carthage.name}}}"
        findFrameworks: true
      {{/each}}
    {{/if}}
    scheme: {} # Generates the shared scheme
  {{#if hasStaticAssets}}
  Static:
    type: bundle
    platform: iOS
    info:
      path: static/Resources-Info.plist
    sources:
      {{#each assetFolderPaths}}
      - path: "{{{this}}}"
        type: folder
      {{/each}}
      {{#each assetCatalogPaths}}
      - "{{{this}}}"
      {{/each}}
  {{/if}}
